### ISSUE TITLE
Drop support for EOL Pythons?

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#127]
This package still supports Python 3.6 and 3.7, [which are EOL](https://endoflife.date/python).

Should support for them be dropped?

**Comment by ajmyyra** [comment]
Hi! We certainly should do so for 3.6. I'm bit on the fence with 3.7 as it was EOL'd just earlier this month, but I guess it doesn't make any sense to postpone this. Out with both. I have some feature needs that need to be added later this month, so I can put out a new release with these dropped then.

**Comment by akx** [comment]
I guess we can be conservative and just drop 3.6 for now 🧹
