### ISSUE TITLE
Unnecessary dependency on py.test

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#15]
The API has a hard dependency on `py.test` -- consumers of the library will thus download `py.test` (and `py`, as a transitive dependency) whenever they `pip install` it.

Unless the library does actually need `py.test` to regularly function (which I doubt 😸) the dependency should moved away from those parsed by `setup.py`.

**Comment by elnygren** [comment]
on its way, among other things :)

https://github.com/UpCloudLtd/upcloud-python-api/commit/6c80b1f4248d63320d027638073c9fd5b3146dab
