### ISSUE TITLE
Requirements are pinned too hard

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#19]
The requirements are pinned to the exact version as it is, which makes it hard to use `pip-tools` or another dependency manager.

Instead of

```
future==0.14.3
mock==1.0.1
requests==2.6.0
responses==0.3.0
six==1.9.0
wheel==0.24.0
```

I suggest something like

```
future>=0.14.3
mock>=1.0.1
requests>=2.6.0
responses>=0.3.0
six
wheel
```

maybe.

**Comment by elnygren** [comment]
@akx I'm not too familiar with `pip-tools` however, I did find this almost immediately from their Readme: http://nvie.com/posts/pin-your-packages/

Seems like `pip-tools` is supposed to be used so that a) packages are pinned exactly and b) the project maintainer updates all dependencies in a controlled fashion from time to time.

Instead of pinning, should I just do a better job at keeping dependencies up to date ?

or am I missing something here?

**Comment by akx** [comment]
pip-tools is nice for end-user projects (i.e. the project I'm working on that uses upcloud-api).

For libraries like upcloud-api, it'd be better to just not pin the dependencies to exact versions, i.e. [use the looser version specifiers](https://www.python.org/dev/peps/pep-0440/#version-specifiers) as in my example above.

In particular, my problem is that I'd like to use `requests==2.10.0` (or whatever's the current version), but `upcloud-api` pins it back to the older version, and trying to explicitly pin it to a higher version in my `pip-tools` `requirements.in` file naturally leads to a conflict; there's no package that satisfies `requests==2.6.0,>=2.10.0` 😆

**Comment by akx** [comment]
Oh, and now that we're talking requirements -- this is a followup to #15 really -- `responses` and `mock` ought to be in dev dependencies only too.

**Comment by elnygren** [comment]
allright, I see your point. Although using strict specifiers guarantees that the library keeps working even if dependencies evolve (and possibly break their APIs), looser specifiers provide a nicer developer experience which should be a priority as this is a tool for developers :)

**Comment by elnygren** [comment]
@akx 

`six` and `requests` are now defined with `>=` :)
https://github.com/UpCloudLtd/upcloud-python-api/blob/0.3.6-devel/requirements.txt
