### ISSUE TITLE
upcloud cli

### ISSUE THREAD

**Issue by szepeviktor** [UpCloudLtd/upcloud-python-api#20]
Do you plan to implement a CLI version?

**Comment by elnygren** [comment]
@szepeviktor we are open to suggestions - however, our development resources can be somewhat limited. 

I suppose this library allows to easily develop a CLI version if one is wanted/needed.

**Comment by szepeviktor** [comment]
Let's do the math: your python experience / mine !DIVISION BY ZERO!

```python
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)

if __name__ == '__main__':
    hello()
```
Seems like a busy project https://github.com/pallets/click/issues
I estimate 2-4 hours (of your time) to release upcloud-cli v0.1.0

All the best!

**Comment by elnygren** [comment]
Thanks! We'll take a look at this. 👍

**Comment by szepeviktor** [comment]
@elnygren Could you start a small *click* project with 2-3 basic commands.
Maybe I will add commands after I see what to do.

**Comment by joglomedia** [comment]
any news about upcloud cli?
