### ISSUE TITLE
`future` not necessarily the best idea

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#21]
So now that we're on the topic of requirements (#15, #19) -- I'm not sure using `future` in a library like this (esp. `future.standard_library.install_aliases()`) is a good idea.

I mean, just importing `upcloud_api` as it is [will install magical `sys.meta_path` hooks](https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L521-L538).

Maybe just use `six` (as it's a dep too anyway)?

**Comment by elnygren** [comment]
if `six` can be easily used to entirely replace `future` (apparently yes) and maintain python 2.6/2.7 support (because ansible), then I'm all aboard this one. 

Adding to 0.3.6 milestone.

**Comment by elnygren** [comment]
@akx 

`future` has been dropped completely at the 0.3.6-devel branch
https://github.com/UpCloudLtd/upcloud-python-api/blob/0.3.6-devel/requirements.txt

**Comment by elnygren** [comment]
oops, for some reason tests passsed even though I was still using `builtins` that is actually part of `future`. Will fix right away.

**Comment by elnygren** [comment]
alright, 0.3.6 released at pypi - sorry for the inconvenience!
