### ISSUE TITLE
Documentation for `user_data` could be better

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#25]
The only docs I can find for the format `user_data`, i.e. bootstrap scripts, is in a blog post https://www.upcloud.com/blog/new-features-initialization-scripts-ssh-keys-increased-resource-limits/ that doesn't even show up if you google for "upcloud user_data".

It would be nice if the API docs (if there's no better general documentation) mentioned that the user data can be cloud-config data too.

**Comment by akx** [comment]
... Never mind. This package apparently doesn't even support `user_data`.

**Comment by elnygren** [comment]
@akx  I have the support ready at the tip of the 0.3.7-devel branch :)
https://github.com/UpCloudLtd/upcloud-python-api/commits/0.3.7-devel
(the actual commit: https://github.com/UpCloudLtd/upcloud-python-api/commit/89898418985d10389723e69d5a537b98579d29f4)

It is a very new feature for UpCloud, but I'll try to prioritise improving the docs of this client as they are lacking a bit. I've tried to summarise new features in the "releases" page (https://github.com/UpCloudLtd/upcloud-python-api/releases) so at least they are mentioned there.

**Comment by akx** [comment]
Sure. :)

For the time being, I'm just doing

```python
from upcloud_api.server import Server
if 'user_data' not in Server.optional_fields:
    # TODO: Remove this when upcloud_api is updated to include:
    #       https://github.com/UpCloudLtd/upcloud-python-api/commit/89898418985d10389723e69d5a537b98579d29f4
    log.info('Patching upcloud_api to include `user_data`.')
    Server.optional_fields.append('user_data')
```

in my app's init phase.
