### ISSUE TITLE
Add hard shutdown and hard restart APIs

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#27]
Currently only soft shutdown and restart APIs are available.

I think this would be most fluently expressed by rephrasing

```python
def shutdown(self):
def restart(self):
```

as

```python
def shutdown(self, hard=False, timeout=30):
def restart(self, hard=False, timeout=30):
```

**Comment by elnygren** [comment]
absolutely, I'll also add timeout_action for server https://www.upcloud.com/api/8-servers/#restart-server while at it.

sane defaults and optional control is the way to go here.

**Comment by elnygren** [comment]
https://github.com/UpCloudLtd/upcloud-python-api/commit/f853c81167ff9218e4878901d0cac9aff5fcfa42
