### ISSUE TITLE
Inaccurate error message when sending invalid `plan` value

### ISSUE THREAD

**Issue by akx** [UpCloudLtd/upcloud-python-api#28]
This isn't exactly a bug in the Python API, but the REST API in general, but I suppose it'll end up in the right place...

Trying to create a server with the `.plan` attribute set to `None` (i.e. serialized to `null` as JSON) fails with

> upcloud_api.errors.UpCloudAPIError: UNKNOWN_ATTRIBUTE The request body contains an unknown attribute server.

(A better error would point at a faulty `plan` attribute.)

When the plan attribute does not exist at all, things work as expected.

**Comment by elnygren** [comment]
our API team verified this and took this into their job queue, so I'm gonna close this here as it does not relate to the API client itself.
