### ISSUE TITLE
Feature Request: Allow avoiding multiple different hosts in avoid_host parameter

### ISSUE THREAD

**Issue by onnimonni** [UpCloudLtd/upcloud-python-api#37]
Sometimes our server instances have really loudy neighbours. This causes slowness in the sites of our clients.

Could you please implement better resource isolation or allow us to avoid multiple different hosts through `avoid_host` parameter?

**Comment by PopoSensei** [comment]
Hello from 2020. Sorry for a very late response. We are currently working on a solution that will handle this.

**Comment by ajmyyra** [comment]
I'm closing this from here as it isn't related to our Python SDK, but is more an API feature.

Closing after this long deserves a longer explanation. We're in the process of deprecating avoid_host altogether and replacing it with some form of affinity groups (for having servers as close or as far from each other). Can't unfortunately promise a precise time for this, but we are well aware of the inadequacy that is our current model and will do better.
