### ISSUE TITLE
Getting started very quickly - examples

### ISSUE THREAD

**Issue by szepeviktor** [UpCloudLtd/upcloud-python-api#49]
Hello!

It took me more than an hour to figure out how to create and destroy a server - as I am a maintenance guy, not into software development.

Could you make the on-boarding easier for others by providing these examples?

https://github.com/szepeviktor/debian-server-tools/blob/master/upcloud_create_server.py
https://github.com/szepeviktor/debian-server-tools/blob/master/upcloud_destroy_server.py

For example in `/examples/`

**Comment by mlackman** [comment]
Thanks, this sounds like a good idea and we will look into your examples.
