### ISSUE TITLE
Deploy server using API

### ISSUE THREAD

**Issue by PhilDarnell** [UpCloudLtd/upcloud-python-api#58]
Hi

I have been having a play around with the API in python and been testing deploying a server but struggling. I'm using requests:

payload = {"server":
                   {"zone": "us-chi1",
                    "title": "Server",
                    "hostname":"example.upcloud.com",
                    "plan":"1xCPU-1GB",
                    "storage_devices":
                        {"storage_device":
                             [{"action": "clone",
                              "storage":"01000000-0000-4000-8000-000050010200",
                              "title": "example.upcloud.com-disk0",
                              "size": 25,
                              "tier": "maxiops"
                              }]
                         }
                    }
               }
    response = requests.request("POST", url, data=payload, headers=headers)
    print(response.text) 

It doesn't like the payload parameter, what have I done wrong?

**Comment by mlackman** [comment]
payload should be converted to json. I think it would be easier to use UpCloud python api instead of doing web requests.

**Comment by PhilDarnell** [comment]
thanks for the help, I've set it up with the UpCloud python api and managed to deploy a server.

Next question, I want to run a script upon the creation of the server, I've tried:

**Comment by PhilDarnell** [comment]
user_data='/createproxy.sh'
Where 'createproxy.sh' is a file in the same folder but it doesn't appear to run the script.

**Comment by mlackman** [comment]
The user_data can be URL for a server setup script, or the script body itself. There is REST api documentation https://developers.upcloud.com/8-servers/#create-server, which can give a glue how to use the api.

**Comment by PhilDarnell** [comment]
Hi, I'm still having trouble using the user_data.

Below is my code, any help is appreciated:

    server_config = Server(
                title='Server',
                plan='1xCPU-1GB',
                hostname='server.darnell.com',
                zone=ZONE.London,
                storage_devices=[
                    Storage(os='CentOS 6.5', size=25),
                ],
                user_data=user_data
                )

    new_server = manager.create_server(server_config)
    print(new_server.get_public_ip())

It creates the server but doesn't load my initialization script.

**Comment by Raiou** [comment]
Hi Phil, the user_data by itself doesn't know how to transfer files. You either need to enter the script as a string or give it a URL the script can be downloaded from. For example:
```
server_config = Server(
            title='Server',
            plan='1xCPU-1GB',
            hostname='server.darnell.com',
            zone=ZONE.London,
            storage_devices=[
                Storage(os='CentOS 6.5', size=25),
            ],
            user_data='yum update -y > ~/update.log'
            )
```
Hope this helps.

**Comment by PhilDarnell** [comment]
Hi Raiou

Thanks for the reply. 

I tried specifying a URL but it seems to just ignore it, 

user_data = 'https://raw.githubusercontent.com/PhilDarnell/proxy/master/createproxy.sh'

**Comment by Raiou** [comment]
Right, it seems the older CentOS template is missing wget which is used by the default during initialization to fetch the script from the URL. It works fine on the newer CentOS 7 template. But if you still want to use the older version, you can simply instruct the init script to use curl instead:
user_data='curl -L https://raw.githubusercontent.com/PhilDarnell/proxy/master/createproxy.sh | sh'

**Comment by PhilDarnell** [comment]
Thanks, I've just tested Cent 6.9 with: 

user_data='curl -L https://raw.githubusercontent.com/PhilDarnell/proxy/master/createproxy.sh | sh'

and it still doesn't seem to load the inialization script, any other ideas?

**Comment by Raiou** [comment]
Apologies for the delay in getting back to you. Tested your script and it did load but it appears your line end coding is using the DOS-style. You'd need to update the script to work on Unix, more about that here https://stackoverflow.com/questions/39527571/are-shell-scripts-sensitive-to-encoding-and-line-endings

For any future reference, the user_data is stored in a script `/etc/upcloud_userdata` and any outputs from the script are logged at `/var/log/upcloud_userdata.log`

**Comment by PopoSensei** [comment]
Hello from 2020. I hope Raiou answered s oit satisfied your problem. I will now close this issue.
