### ISSUE TITLE
Please make add a release tag for upcloud-api-0.4.5

### ISSUE THREAD

**Issue by onkelbeh** [UpCloudLtd/upcloud-python-api#63]
Hi Wil,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository). Therefor I need a release file in tar.gz format.
Home Assistant currently requires: `upcloud-api-0.4.5`

This one exists at Pypi, but only in wheel format, cannot use this.

Generally, a tar.gz release on Pypi (sdist) would be preferred, because this could take use of Gentoo's mirror system.

Most of the other integrations do both.

Thanks
 \B.

**Comment by onkelbeh** [comment]
anybody home here?

**Comment by onkelbeh** [comment]
knock-knock?

**Comment by LordChocoBlizzBallz** [comment]
PyPI is now hosting upcloud-api-0.4.5.tar.gz

Give it a go and let me know if there are any issues!

**Comment by onkelbeh** [comment]
Compiles & installs. Thanks.
